### ISSUE TITLE
Error: Connection to rabbit@ cannot be established

### ISSUE THREAD

**Issue by olazt** [Esri/rabbitmq-for-geoevent#10]
Hi, I have deployed Rabbit MQ transport and created Input Connector which receives text form Rabbit MQ. I was trying to follow the tutorial: http://www.arcgis.com/home/item.html?id=b1da75d6f2874c7ba31ef15c6da2e86b but with the use of rabbitmq-transport-10.6.0.jar file from here. 

I have my RabbitMQ cluster running on the same machine (Windows Server 2019) with ArcGIS Server and GeoEvent Extension. However, I cannot make input working as I constantly gets an error. First, just after adding the input the Status is: 
**Error - Connection to rabbit@computername is broken,** 
after couple of seconds it transforms to the status: 
**Error - Connection to rabbit@computername cannot be established,** 
and after while computername dissapears. 
![pic](https://user-images.githubusercontent.com/47882216/61537016-54d96500-aa36-11e9-9128-849b6a72d70c.png)

Here is the copy of the log message:

Failed to create connection cxn-195	java.io.IOException: null		at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:376) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:617) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:243) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:236) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.internal.RetryableResource.callWithRetries(RetryableResource.java:51) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:236) ~[474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:119) [474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at net.jodah.lyra.Connections.create(Connections.java:68) [474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at com.esri.geoevent.transport.rabbitmq.RabbitMQConnectionBroker$RabbitMQConnectionMonitor.run(RabbitMQConnectionBroker.java:163) [474:com.esri.geoevent.transport.rabbitmq-transport:10.7.0]		at java.lang.Thread.run(Thread.java:748) [?:?]	Caused by: com.rabbitmq.client.ShutdownSignalException: connection error		at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67) ~[?:?]		at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33) ~[?:?]		at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:343) ~[?:?]		at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:216) ~[?:?]		at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118) ~[?:?]		... 10 more	Caused by: java.net.SocketException: Connection reset		at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:?]		at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:?]		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:?]		at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:?]		at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[?:?]		at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[?:?]		at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[?:?]		at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:534) ~[?:?]		... 1 more
--

I though this post (https://community.esri.com/thread/191847-geoevent-services-not-producing-any-inout-results) could help but antivirus software is not a problem here.

Are you familiar with the problem and can suggest any solution?

Regards

**Comment by brysageek** [comment]
I've had this issue in the past with this, in some of the old documentation available on the Gallery Tutorials for RabbitMQ importable xml files--issue here is that don't match up with the  build release of 10.6, there will end up only being one host property configured in the connectors shown properties--there is in fact two. one is for the Virtual host, the other is for the RabbitMQ hostname.  The virtual host will not default to "\\" but instead is left as a blank string  you will need to set this to "\\" or whatever you've got configured.  What I had to do was actually go in and configure the connecter from scratch and provide the two hosts in the shown properties--you may also be able to alter the xml and get the host over from hidden to shown.  I will see if I can't find in code where the properties could differentiate-- I don't get a lot of time to work on this so no promises
