### ISSUE TITLE
ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN

### ISSUE THREAD

**Issue by LuisRguezEsriSpain** [Esri/rabbitmq-for-geoevent#4]
Hi,

I've deployed RabbitMQ connector and have created a input connector with Rabbit Transport and Generic-JSON Adapter. Then, I've created a input.

These are the configuration Input's properties:
host=10.5.30.200
port=5672
virtualHost=/
username=user
password=password
#password=kk
ssl=false
exchangeName=inbound
exchangeType=direct
exchangeDurability=Durable
exchangeAutoDelete=true
routingKey=
queueName=FLEETCAR2GO.flotapos
queueDurability=Durable
queueExclusive=false
queueAutoDelete=true
prefetchCount=1

The input throws this exeption:
2018-05-24T16:59:13,530 | ERROR | Thread-68        | ConnectionHandler                | 54 - com.esri.ges.framework.messaging.jms-messaging - 10.6.0 | Failed to create connection cxn-34
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:349) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:911) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:870) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:786) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:233) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:227) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.internal.RetryableResource.callWithRetries(RetryableResource.java:50) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:227) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:115) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at net.jodah.lyra.Connections.create(Connections.java:68) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at com.esri.ges.messaging.jms.amqp.AmqpMessagingFactory$ConnectionEstablisher.run(AmqpMessagingFactory.java:1035) [54:com.esri.ges.framework.messaging.jms-messaging:10.6.0]
	at java.lang.Thread.run(Thread.java:748) [?:?]

The user and password are correct.

Any idea about the cause of this problem?

Regards

**Comment by LuisRguezEsriSpain** [comment]
I'm using GeoEvent 10.6.

**Comment by LuisRguezEsriSpain** [comment]
Hi,

I've already solve this issue. I did the steps of connector's tutorial but I adapted the steps to ArcGIS 10.6, and I also changed the configuration Input's properties.

Regards.

**Comment by jhjoyner1** [comment]
@LuisRguezEsriSpain I'm glad to hear you were able to address this issue. We're targeting several changes to the documentation for these add-on components and will make sure we review those steps before porting them over into the new format. Thank you for reporting the issue and bringing it to our attention. I'll capture the details through our internal backlog and mark this issue as closed.

cc: @vplechnoy
